// If you are AI: This file holds the longer document templates so that no single
// .go file in scripts/gen-docs exceeds the 300-line limit enforced by check-lines.

package main

import (
	"os"
	"path/filepath"
)

// writeTesting writes the TESTING.md document describing the test layers.
func writeTesting(dir string) error {
	body := `<!--
If you are AI: This file describes how to run tests for nonchalant.
It is generated by scripts/gen-docs and should be updated when test structure changes.
-->

# Testing

nonchalant has three test layers, each with a different blast radius:

| Layer         | Lives in              | Drives                                          | Requires                 |
| ------------- | --------------------- | ----------------------------------------------- | ------------------------ |
| Unit          | ` + "`internal/**/*_test.go`" + ` | Pure Go packages, table-driven tests        | Go toolchain             |
| Integration   | ` + "`internal/itest`" + `        | Real binary on ephemeral ports + ffmpeg CLI | ffmpeg on PATH           |
| E2E (browser) | ` + "`e2e/`" + `                  | Real binary + ffmpeg + Chromium via flv.js  | ffmpeg + Node + Chromium |

## Unit Tests

` + "```" + `
make test          # all packages
make test-short    # short-mode only
make test-race     # with the race detector
make bench         # benchmarks (internal/core/bus)
` + "```" + `

## Integration Tests

Spin up the real binary on free ports, drive it with ` + "`ffmpeg`" + ` as a publisher,
and assert via the FLV / WS-FLV / HLS / DASH / API surface.

` + "```" + `
make itest
` + "```" + `

Coverage today (` + "`internal/itest/`" + `):

- ` + "`itest_test.go`" + ` - clean startup + SIGINT shutdown
- ` + "`api_test.go`" + ` - HTTP API endpoints
- ` + "`auth_test.go`" + ` - publish-key authentication accept / reject
- ` + "`rtmp_connect_test.go`" + ` - RTMP handshake / connect / publish
- ` + "`rtmp_test.go`" + ` - RTMP ingest end-to-end
- ` + "`httpflv_test.go`" + ` - publish via RTMP, consume via HTTP-FLV, verify FLV bytes
- ` + "`wsflv_test.go`" + ` - publish via RTMP, consume via WebSocket-FLV
- ` + "`hls_test.go`" + ` / ` + "`dash_test.go`" + ` - FLV → external ffmpeg HLS / DASH (legacy)
- ` + "`native_hls_test.go`" + ` - the built-in /hls/* and /dash/* endpoints

Tests that need ` + "`ffmpeg`" + ` skip themselves when it is not on PATH.

## End-to-End (Browser) Tests

Playwright drives a real Chromium instance through the WebSocket-FLV path and
asserts that ` + "`flv.js`" + ` decodes the live stream into a ` + "`<video>`" + ` whose
` + "`currentTime`" + ` advances. See ` + "`e2e/README.md`" + ` for details.

` + "```" + `
make e2e-install   # one-time: install Playwright + Chromium
make e2e           # run the suite
make e2e-headed    # watch the browser
make e2e-report    # open the last HTML report
` + "```" + `

## Lint

` + "```" + `
make lint          # golangci-lint v2 (config in .golangci.yml)
` + "```" + `

## Aggregate Checks

` + "```" + `
make check         # fmt + line limit + header + docs + unit tests
` + "```" + `

This is what CI gates on. ` + "`make itest`" + `, ` + "`make e2e`" + `, and ` + "`make lint`" + ` are run as
separate CI jobs because they are slower and require external tooling.
`
	return os.WriteFile(filepath.Join(dir, "TESTING.md"), []byte(body), 0644)
}

// writeOps writes OPERATIONS.md describing the metrics endpoint and ops surface.
func writeOps(dir string) error {
	body := `<!--
If you are AI: This file documents the operational endpoints — health, metrics, and API.
Generated by scripts/gen-docs.
-->

# Operations

## Endpoints

| Path                          | Purpose                                                  |
| ----------------------------- | -------------------------------------------------------- |
| ` + "`/healthz`" + `                    | Liveness probe (200 if process is up).                  |
| ` + "`/metrics`" + `                    | Prometheus text-format metrics (process, Go, custom).   |
| ` + "`/api/server`" + `                 | Server version, uptime, enabled services.               |
| ` + "`/api/streams`" + `                | Per-stream publisher / subscriber / drop counters.      |
| ` + "`/api/relay`" + `                  | Configured relay tasks and running flag.                |
| ` + "`/api/relay/restart`" + `          | POST {app, name} to restart a relay task.               |
| ` + "`/{app}/{name}.flv`" + `           | HTTP-FLV live playback.                                 |
| ` + "`/ws/{app}/{name}`" + `            | WebSocket-FLV live playback.                            |
| ` + "`/hls/{app}/{name}.m3u8`" + `      | Native HLS playlist + .ts segments under the prefix.    |
| ` + "`/dash/{app}/{name}.mpd`" + `      | Native MPEG-DASH manifest + .m4s chunks under prefix.   |

## Metrics

The ` + "`/metrics`" + ` endpoint emits Prometheus text format. Custom metrics:

- ` + "`nonchalant_streams`" + ` (gauge): registered streams.
- ` + "`nonchalant_publishers`" + ` (gauge): streams with a publisher.
- ` + "`nonchalant_subscribers{app,name}`" + ` (gauge): subscribers per stream.
- ` + "`nonchalant_messages_published_total{app,name}`" + ` (counter).
- ` + "`nonchalant_messages_dropped_total{app,name}`" + ` (counter — backpressure drops).
- ` + "`nonchalant_relay_tasks`" + ` (gauge).

Standard ` + "`go_*`" + ` and ` + "`process_*`" + ` collectors are also exposed.

## Authentication

Set ` + "`auth.publish_keys`" + ` to require a pre-shared secret on every RTMP
publish; ` + "`auth.play_keys`" + ` does the same for HTTP-FLV / WS-FLV / HLS / DASH
subscribers. Both pass the secret as ` + "`?key=<secret>`" + `:

` + "```" + `
ffmpeg ... -f flv 'rtmp://host:1935/live/mystream?key=changeme'
ffplay 'http://host:8081/live/mystream.flv?key=watch-secret'
` + "```" + `

Either field may be omitted to allow anonymous access in that direction.

## Native HLS / DASH

The packager spawns one ` + "`ffmpeg`" + ` subprocess per (stream, format) on first
request. It pulls the server's own HTTP-FLV output and writes segments to a
temp directory. Subprocesses are GC'd 60 s after their last access; SIGKILL
is sent on server shutdown. ` + "`ffmpeg`" + ` must be on the server's PATH; if
absent the endpoints return 503.

### Single rendition (default)

When ` + "`hls.ladder`" + ` is empty the packager runs in stream-copy mode (no
transcoding, ~zero CPU). Output URLs:

- ` + "`/hls/{app}/{name}.m3u8`" + ` — playlist
- ` + "`/hls/{app}/{name}/seg_NNNNN.ts`" + ` — TS segments
- ` + "`/dash/{app}/{name}.mpd`" + ` — DASH manifest

### ABR (multi-bitrate)

When ` + "`hls.ladder`" + ` is non-empty the packager transcodes one rendition per
rung with ` + "`libx264`" + `. Output URLs:

- ` + "`/hls/{app}/{name}.m3u8`" + ` — master playlist (lists all rungs)
- ` + "`/hls/{app}/{name}/{rung}/index.m3u8`" + ` — per-rendition media playlist
- ` + "`/hls/{app}/{name}/{rung}/seg_NNNNN.ts`" + ` — per-rendition TS segments
- ` + "`/dash/{app}/{name}.mpd`" + ` — DASH manifest with one Representation per
  video rung in a single AdaptationSet

ABR cost is dominated by H.264 encoding. Pick ladder rungs with care; use
hardware acceleration if you need many rungs at high resolution.
`
	return os.WriteFile(filepath.Join(dir, "OPERATIONS.md"), []byte(body), 0644)
}
