// If you are AI: This script generates documentation files from code and configuration.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// main generates documentation files from code templates and writes them to the docs directory.
func main() {
	docsDir := "docs"
	if err := os.MkdirAll(docsDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create docs directory: %v\n", err)
		os.Exit(1)
	}

	for name, fn := range generators() {
		if err := fn(docsDir); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to write %s: %v\n", name, err)
			os.Exit(1)
		}
	}

	stamp := fmt.Sprintf("%d\n", time.Now().Unix())
	if err := os.WriteFile(filepath.Join(docsDir, ".stamp"), []byte(stamp), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write .stamp: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Documentation generated successfully")
}

// generators returns the per-document writer functions keyed by output filename.
func generators() map[string]func(string) error {
	return map[string]func(string) error{
		"ARCHITECTURE.md": writeArchitecture,
		"CONFIG.md":       writeConfig,
		"TESTING.md":      writeTesting,
		"OPERATIONS.md":   writeOps,
	}
}

// writeArchitecture writes the ARCHITECTURE.md document describing system layout.
func writeArchitecture(dir string) error {
	body := `<!--
If you are AI: This file describes the architecture of the nonchalant server.
It is generated by scripts/gen-docs.go and should be updated when structure changes.
-->

# Architecture

## Overview

nonchalant is a high-performance media server written in Go. Reusable core
logic (stream bus, protocol codecs) is separated from network-facing services
(RTMP ingest, HTTP-FLV, WebSocket-FLV, HLS, DASH, relay, API, metrics).
Inbound media is normalised onto an in-memory bus, and every output service is
just a subscriber.

## Directory Structure

- ` + "`cmd/nonchalant/`" + ` - Main entrypoint: configuration, server startup, signal handling
- ` + "`internal/config/`" + ` - YAML configuration loading and validation
- ` + "`internal/server/`" + ` - Top-level server lifecycle and graceful shutdown
- ` + "`internal/core/bus/`" + ` - Stream registry, ring-buffered subscribers, fan-out
- ` + "`internal/core/protocol/amf0/`" + ` - AMF0 encode/decode for RTMP commands
- ` + "`internal/core/protocol/flv/`" + ` - FLV header / tag muxing
- ` + "`internal/core/protocol/rtmp/`" + ` - RTMP chunk, message, handshake
- ` + "`internal/svc/health/`" + ` - ` + "`/healthz`" + ` endpoint
- ` + "`internal/svc/rtmp/`" + ` - RTMP ingest with optional publish-key authentication
- ` + "`internal/svc/httpflv/`" + ` - HTTP-FLV output
- ` + "`internal/svc/wsflv/`" + ` - WebSocket-FLV output
- ` + "`internal/svc/pkger/`" + ` - HLS / DASH packager (spawns ffmpeg subprocesses)
- ` + "`internal/svc/relay/`" + ` - RTMP pull / push relay tasks
- ` + "`internal/svc/api/`" + ` - HTTP API
- ` + "`internal/svc/metrics/`" + ` - Prometheus ` + "`/metrics`" + ` endpoint
- ` + "`internal/svc/transcode/`" + ` - Optional transcode pipeline (build tag ` + "`ffmpeg`" + `)
- ` + "`internal/ffx/`" + ` - cgo wrapper around FFmpeg libs (build tag ` + "`ffmpeg`" + `)
- ` + "`internal/itest/`" + ` - Integration tests that drive the real binary
- ` + "`e2e/`" + ` - Playwright browser end-to-end tests
- ` + "`scripts/`" + ` - Code-quality enforcement and doc generation
- ` + "`.github/workflows/`" + ` - CI pipeline (check, integration, e2e)

## Data Flow

1. Publishers connect over RTMP. If ` + "`auth.publish_keys`" + ` is configured the
   publisher must include ` + "`?key=<secret>`" + ` in the stream name; otherwise the
   publish is rejected with ` + "`NetStream.Publish.Failed`" + `.
2. Audio/video tags are decoded once and pushed onto a stream-keyed channel in
   ` + "`internal/core/bus`" + `. The bus caches the FLV header plus AVC and AAC
   sequence headers so late subscribers can join mid-stream.
3. Each output service subscribes to the bus and writes the cached headers
   followed by live tags. HTTP-FLV streams over chunked HTTP; WebSocket-FLV
   streams over a binary WebSocket; HLS / DASH spawn an ffmpeg subprocess that
   pulls our own HTTP-FLV stream and writes segments to a temp dir served by
   the packager handler; the relay republishes via an outbound RTMP client.
4. The HTTP API and Prometheus metrics endpoint read registry state for
   introspection — including per-stream message counts and drop totals.

## Server Lifecycle

1. Main process loads configuration from YAML (path from ` + "`--config`" + `).
2. Stream registry, RTMP ingest server, HTTP server (FLV + WS + HLS + DASH +
   API + ` + "`/metrics`" + `), relay manager, and health server are all started.
3. Shutdown handler listens for SIGINT/SIGTERM.
4. On signal, every subsystem is given a 5-second graceful shutdown window;
   FLV / WS-FLV handlers exit on request-context cancellation, HLS / DASH
   ffmpeg subprocesses receive SIGKILL, listeners close, and in-flight relays
   are drained.
5. Process exits cleanly.

## Build Tags

- Default build: pure Go plus ` + "`gopkg.in/yaml.v3`" + `, ` + "`github.com/gorilla/websocket`" + `, and ` + "`github.com/prometheus/client_golang`" + `.
- ` + "`-tags ffmpeg`" + `: enables the cgo-backed transcode pipeline. Requires libavformat / libavcodec / libavutil at link time.

## Roadmap Status

Phases 1-9 complete: configuration, stream bus, RTMP ingest, HTTP-FLV,
WebSocket-FLV, RTMP relay, HTTP API, FFmpeg integration, plus the
post-Phase-8 hardening — publish authentication, native HLS / DASH endpoints,
Prometheus metrics, lint config, and CI.
`
	return os.WriteFile(filepath.Join(dir, "ARCHITECTURE.md"), []byte(body), 0644)
}

// writeConfig writes the CONFIG.md document describing the YAML schema.
func writeConfig(dir string) error {
	body := `<!--
If you are AI: This file describes the configuration schema for nonchalant.
It is generated by scripts/gen-docs.go and should be updated when config structure changes.
-->

# Configuration

## Format

Configuration is YAML-only. Unknown fields are rejected.

## Schema

` + "```yaml" + `
server:
  health_port: 8080  # Port for /healthz endpoint (1-65535)
  http_port:   8081  # Port for HTTP-FLV, WS-FLV, HLS, DASH, API, /metrics
  rtmp_port:   1935  # Port for RTMP ingest

auth:                 # Optional. Omit for anonymous publishing/playback.
  publish_keys:       # Pre-shared secrets accepted on RTMP publish.
    - changeme        # rtmp://host/live/foo?key=changeme
  play_keys:          # Pre-shared secrets accepted on FLV/WS/HLS/DASH playback.
    - watch-secret    # http://host/live/foo.flv?key=watch-secret

hls:                  # Optional HLS / DASH packager tuning.
  low_latency: false  # When true: 1s fMP4 segments, LL-HLS friendly.
  ladder:             # Optional ABR (multi-bitrate) renditions.
    - {name: 720p,  width: 1280, height: 720, video_bitrate: 2500}
    - {name: 480p,  width: 854,  height: 480, video_bitrate: 1100}
    - {name: 240p,  width: 426,  height: 240, video_bitrate: 400}
    - {name: audio, audio_only: true, audio_bitrate: 64}

relays:               # Optional. Each entry runs as a managed task.
  - app: live
    name: mystream
    mode: pull        # "pull" (remote → local) or "push" (local → remote)
    remote_url: rtmp://remote-server:1935/live/source
    reconnect: true
    max_retries: 5
    retry_delay_seconds: 5
` + "```" + `

## Validation Rules

- All ports must be between 1 and 65535.
- All ports must be unique across ` + "`health_port`" + `, ` + "`http_port`" + `, and ` + "`rtmp_port`" + `.
- Default values are applied when a section is omitted.
- Each relay requires ` + "`app`" + `, ` + "`name`" + `, ` + "`mode`" + `, and ` + "`remote_url`" + `.
- ` + "`auth.publish_keys`" + ` is optional. When present and non-empty, every publisher
  must include ` + "`?key=<secret>`" + ` in the RTMP stream name.
- Each ` + "`hls.ladder`" + ` rung needs a unique alphanumeric ` + "`name`" + ` (no slashes / dots).
  Video rungs require ` + "`width`" + `, ` + "`height`" + `, and ` + "`video_bitrate`" + ` (kbit/s).
  Audio-only rungs set ` + "`audio_only: true`" + ` and may set ` + "`audio_bitrate`" + `.

## ABR / multi-bitrate notes

- An empty ` + "`hls.ladder`" + ` runs the packager in stream-copy mode: one ffmpeg
  per stream, no transcoding, ~zero CPU. The default.
- A non-empty ladder runs ` + "`libx264`" + ` per video rung. CPU is roughly
  ` + "`Σ rungs`" + ` × bitrate-dependent. Consider hardware acceleration if you
  configure many rungs.
- Per-rendition URLs follow ` + "`/hls/{app}/{name}/{rung}/index.m3u8`" + ` and
  ` + "`/hls/{app}/{name}/{rung}/seg_NNNNN.ts`" + `.
- DASH's MPD lists each video rung as a Representation under one
  AdaptationSet automatically.

## Loading

Configuration is loaded via the ` + "`--config`" + ` flag:

` + "```" + `
./nonchalant --config configs/nonchalant.example.yaml
` + "```" + `

Default path is ` + "`configs/nonchalant.example.yaml`" + `.
`
	return os.WriteFile(filepath.Join(dir, "CONFIG.md"), []byte(body), 0644)
}
