// If you are AI: This script generates documentation files from code and configuration.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// main generates documentation files from code templates and writes them to the docs directory.
func main() {
	docsDir := "docs"
	if err := os.MkdirAll(docsDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create docs directory: %v\n", err)
		os.Exit(1)
	}

	// Generate ARCHITECTURE.md
	archContent := `<!--
If you are AI: This file describes the architecture of the nonchalant server.
It is generated by scripts/gen-docs.go and should be updated when structure changes.
-->

# Architecture

## Overview

nonchalant is a high-performance media server written in Go. It follows a modular architecture where core logic is separated from network-facing services.

## Directory Structure

- cmd/nonchalant/ - Main entrypoint that handles configuration, server startup, and graceful shutdown
- internal/config/ - YAML configuration loading and validation
- internal/server/ - HTTP server lifecycle and graceful shutdown orchestration
- internal/svc/health/ - Health check endpoint for monitoring
- internal/itest/ - Integration tests that verify server behavior

## Server Lifecycle

1. Main process loads configuration from YAML file
2. Server is created with health endpoint
3. Server starts listening on configured port
4. Shutdown handler listens for SIGINT/SIGTERM
5. On signal, server gracefully shuts down with 5-second timeout
6. Process exits cleanly

## Configuration

Configuration is loaded from YAML files with strict validation. Unknown fields are rejected. See docs/CONFIG.md for schema details.

## Future Phases

This is Phase 1. Future phases will add:
- Stream bus and registry (Phase 2)
- RTMP ingest (Phase 3)
- HTTP-FLV output (Phase 4)
- WebSocket-FLV output (Phase 5)
- RTMP relay (Phase 6)
- HTTP API (Phase 7)
- FFmpeg integration (Phase 8)
`

	if err := os.WriteFile(filepath.Join(docsDir, "ARCHITECTURE.md"), []byte(archContent), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write ARCHITECTURE.md: %v\n", err)
		os.Exit(1)
	}

	// Generate CONFIG.md
	configContent := "<!--\n" +
		"If you are AI: This file describes the configuration schema for nonchalant.\n" +
		"It is generated by scripts/gen-docs.go and should be updated when config structure changes.\n" +
		"-->\n\n" +
		"# Configuration\n\n" +
		"## Format\n\n" +
		"Configuration is YAML-only. Unknown fields are rejected.\n\n" +
		"## Schema\n\n" +
		"```yaml\n" +
		"server:\n" +
		"  health_port: 8080  # Port for health endpoint (1-65535)\n" +
		"  http_port: 8081    # Port for future HTTP services (1-65535)\n" +
		"  rtmp_port: 1935    # Port for future RTMP service (1-65535)\n" +
		"```\n\n" +
		"## Validation Rules\n\n" +
		"- All ports must be between 1 and 65535\n" +
		"- All ports must be unique (no duplicates)\n" +
		"- Default values are applied if not specified\n\n" +
		"## Loading\n\n" +
		"Configuration is loaded via the --config flag:\n" +
		"```\n" +
		"./nonchalant --config configs/nonchalant.example.yaml\n" +
		"```\n\n" +
		"Default path is configs/nonchalant.example.yaml.\n"

	if err := os.WriteFile(filepath.Join(docsDir, "CONFIG.md"), []byte(configContent), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write CONFIG.md: %v\n", err)
		os.Exit(1)
	}

	// Generate TESTING.md
	testContent := "<!--\n" +
		"If you are AI: This file describes how to run tests for nonchalant.\n" +
		"It is generated by scripts/gen-docs.go and should be updated when test structure changes.\n" +
		"-->\n\n" +
		"# Testing\n\n" +
		"## Unit Tests\n\n" +
		"Run unit tests with:\n" +
		"```\n" +
		"make test\n" +
		"```\n\n" +
		"Or directly:\n" +
		"```\n" +
		"go test ./...\n" +
		"```\n\n" +
		"## Integration Tests\n\n" +
		"Integration tests verify server startup, health checks, and graceful shutdown:\n" +
		"```\n" +
		"make itest\n" +
		"```\n\n" +
		"Integration tests:\n" +
		"- Build the server binary\n" +
		"- Start it on a free port\n" +
		"- Wait for /healthz endpoint\n" +
		"- Send SIGINT\n" +
		"- Verify clean shutdown within 2 seconds\n\n" +
		"## Test Targets\n\n" +
		"- make test - Run all unit tests\n" +
		"- make test-short - Run short tests only\n" +
		"- make test-race - Run tests with race detector\n" +
		"- make bench - Run benchmarks\n" +
		"- make itest - Run integration tests\n" +
		"- make itest-clean - Clean integration test artifacts\n"

	if err := os.WriteFile(filepath.Join(docsDir, "TESTING.md"), []byte(testContent), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write TESTING.md: %v\n", err)
		os.Exit(1)
	}

	// Write stamp file
	stamp := fmt.Sprintf("%d\n", time.Now().Unix())
	if err := os.WriteFile(filepath.Join(docsDir, ".stamp"), []byte(stamp), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write .stamp: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Documentation generated successfully")
}
